name: Docker Build and Run

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t test_image .

    - name: Run Docker container
      run: docker run -e API_KEY=$TEST_API_KEY -d test_image --name test_container

    - name: Get container exit code and set as env var
      run: echo "CONTAINER_EXIT_CODE=$(docker inspect test_container --format='{{.State.ExitCode}}')" >> $GITHUB_ENV

    - name: Print container exit code
      run: echo "Container exit code is $CONTAINER_EXIT_CODE"
    
    - name: Fail if exit code is not 0
      run: |
        if [[ "$CONTAINER_EXIT_CODE" != "0" ]]; then
          echo "error=Container failed with exit code $CONTAINER_EXIT_CODE" >> $GITHUB_ENV
          exit 1
        fi

    - name: Cleanup
      run: docker rm test_container
      if: always()
